
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Iskatel.Model.ORM
{

using System;
    using System.Collections.Generic;
    
public partial class Class
{

    public int Id { get; set; }

    public Nullable<int> ParentId { get; set; }

    public Nullable<int> TypeClassId { get; set; }

    public string Alias { get; set; }

}

}
