
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Iskatel.Model.ORM
{

using System;
    using System.Collections.Generic;
    
public partial class Data
{

    public int Id { get; set; }

    public Nullable<int> EntityId { get; set; }

    public string RelationId { get; set; }

    public Nullable<int> ClassId { get; set; }

    public Nullable<int> LangId { get; set; }

    public string Data1 { get; set; }

}

}
