//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iskatel.Model.ORM
{
    using System;
    using System.Collections.Generic;
    public partial class Data
    {
        public int Id { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string RelationId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> LangId { get; set; }
        public string Data1 { get; set; }
    }
}
