//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iskatel.Model.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> DestinationId { get; set; }
    }
}
