//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iskatel.DataAccess.SQLServices.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iskateli_devEntities : DbContext
    {
        public iskateli_devEntities()
            : base("name=iskateli_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Data> Data { get; set; }
        public virtual DbSet<Entity> Entity { get; set; }
        public virtual DbSet<Relation> Relation { get; set; }
    }
}
